name: minedb
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - conda=4.9.2
  - conda-build=3.21.4
  - conda-package-handling=1.7.2
  - coverage=5.5
  - cryptography=3.4.6
  - cycler=0.10.0
  - decorator=4.4.2
  - docutils=0.16
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.67.4
  - glob2=0.7
  - icu=68.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.3
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lcms2=2.11
  - libarchive=3.4.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran5=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblief=0.10.1
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.1
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - more-itertools=8.7.0
  - ncurses=6.2
  - numpy=1.20.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.3
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - pkginfo=1.7.0
  - pluggy=0.12.0
  - prompt-toolkit=3.0.8
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycairo=1.19.1
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.8.1
  - pymongo=3.11.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.2
  - pytest-cov=2.11.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python-libarchive-c=2.9
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=20.0.0
  - rdkit=2020.09.5
  - readline=8.1
  - reportlab=3.5.60
  - requests=2.25.1
  - ripgrep=12.1.1
  - ruamel_yaml=0.15.80
  - setuptools=52.0.0
  - six=1.15.0
  - snowballstemmer=2.1.0
  - soupsieve=2.2
  - sphinx=3.5.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlalchemy=1.3.23
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - tzdata=2020f
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appnope==0.1.2
    - appdirs==1.4.4
    - black==20.8b1
    - click==7.1.2
    - distlib==0.3.1
    - dnspython==1.16.0
    - docopt==0.6.2
    - dparse==0.5.1
    - fett==0.3.2
    - flake8==3.8.4
    - flake8-bugbear==21.3.2
    - flake8-docstrings==1.5.0
    - isort==5.7.0
    - mccabe==0.6.1
    - mordred==1.2.0
    - mypy-extensions==0.4.3
    - networkx==2.5
    - pathspec==0.8.1
    - pockets==0.9.1
    - pycodestyle==2.6.0
    - pydocstyle==5.1.1
    - pyflakes==2.2.0
    - python-jsonrpc-server==0.3.4
    - pyyaml==5.4.1
    - regex==2020.11.13
    - rstcheck==3.3.1
    - safety==1.10.3
    - scipy==1.6.1
    - snooty-lextudio==1.8.10.dev0
    - sphinxcontrib-napoleon==0.7
    - tox==3.23.0
    - typed-ast==1.4.2
    - typing-extensions==3.7.4.3
    - ujson==1.35
    - virtualenv==20.4.2
    - watchdog==1.0.2
